name: Lua Checks

on:
    workflow_dispatch: 
    push:
        branches: 
            - main
    pull_request: 
        branches: 
            - main
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@4
            - name: Luacheck
              uses: lunarmodules/luacheck@v1.1.0
              with:
                args: . --no-max-line-length -o 121 512 542 --globals os _HOST bit colors fs http keys parallel periphemu peripheral read rs settings shell term textutils window